### PR TITLE
Implement tag and search features

### LINKED ISSUE #23: implement tag and search for the blogs in webpage

### LINKED ISSUE #31: implement search
make blog search able

### LINKED ISSUE #32: add tag for blog
add tag for blog

### PR DESCRIPTION
**Pull request by keyboard2543**
I fixed conflicts and the feature about tag and search can be used. Let test it before we merge!

### CODE REVIEW

**Comment by keyboard2543** [comment]
I fixed conflicts and the feature about tag and search can be used. Let test it

**Comment by NarawishS** [comment]
Why does we need to add tags in admin before we are able to tags in blog?

**Comment by NarawishS** [comment]
please add filter for tag in edit blog too

**Comment by keyboard2543** [comment]
>  @NarawishS please add filter for tag in edit blog too
`Ok, I added`


> @NarawishS Why does we need to add tags in admin before we are able to tags in blog?
`Now users can add tag by themselve`

**Comment by NarawishS** [comment]
+1 form look a little bad but it's work fine GOODJOB BRO

**Comment by LevNut** [comment]
+1, it works!

**Comment by Bheem6005** [comment]
+1 work fine now

**Pull request merged**
