### PR TITLE
Blog Forum new features and bug fixes

### PR DESCRIPTION
**Pull request by keyboard2543**
New important features:
- Bug fixes: Duplicate Forum fixes.
- While logging in with superuser. You can add or delete Forum. Superuser not need to go to admin page to add or delete Forum.
- Confirm delete Forum alert when a superuser going to delete Forum in Forum index page.

### CODE REVIEW

**Comment by NarawishS** [comment]
This branch didn't use the current master as base
The older commit of this branch is even commit ahead of this one
You're making my work harder now

**Comment by NarawishS** [comment]
function work fine good

**Review by NarawishS — COMMENTED** [review]
good work

**Comment by Bheem6005** [comment]
+1 working good

**Comment by LevNut** [comment]
+1 this work fine, good job

**Pull request merged**
