### PR TITLE
Blog forum feature

### LINKED ISSUE #54: Implement forum feature
Forum for blogs.

### PR DESCRIPTION
**Pull request by keyboard2543**
New pages are added:
- Index page to show all of the forum.
- Detail page for the forum.

### CODE REVIEW

**Review by NarawishS — COMMENTED** [review]
A lot of ghost file, i have to delete some useless old code for you

**Comment by NarawishS** [comment]
+1 looking good for now

**Comment by Bheem6005** [comment]
+1 working fine

**Comment by LevNut** [comment]
+1, addable forum, working fine

**Comment by NarawishS** [comment]
i am resolving conflicts now

**Comment by NarawishS** [comment]
I finish fix some old model and html for old blog model

**Comment by LevNut** [comment]
After resolving conflicts, the forum feature is working normally

**Pull request merged**
