### PR TITLE
Add comment delete feature

### LINKED ISSUE #34: make comment delete able
add delete for comment

### PR DESCRIPTION
**Pull request by Bheem6005**
- add comment delete feature
- implement some navigation

### CODE REVIEW

**Comment by NarawishS** [comment]
you need to make only author of comment delete able only

**Comment by NarawishS** [comment]
+1 work now good job

**Comment by keyboard2543** [comment]
+1 It can really delete the comment

**Comment by LevNut** [comment]
+1, work fine for deleting comments

**Pull request merged**
