### PR TITLE
Implement like/dislike button to comments

### LINKED ISSUE #35: add like and dislike to blog and comment

### PR DESCRIPTION
**Pull request by LevNut**
- add like/dislike button to comment
- fixing some template on `blog-detail.html`

### CODE REVIEW

**Comment by NarawishS** [comment]
There seem to be error, you can't like multiple comment in one blog, when i like first comment it work but other change like and dislike too.

**Comment by LevNut** [comment]
@NarawishS Thanks for checking the features, I will try to fix as soon as possible

**Comment by NarawishS** [comment]
+1 ok i think it work now, still think you can make template look better though

**Comment by keyboard2543** [comment]
+1 It is work now. I have tested in multiple comment. Outcome is true as we expected.

**Comment by Bheem6005** [comment]
+1 working fine for now

**Pull request merged**
