### PR TITLE
Create Comment model & view

### LINKED ISSUE #33: create comment section for each blog
create comment for blog

### PR DESCRIPTION
**Pull request by Bheem6005**
- create Comment model
- create create_blog.html
-  implement blog_detail.html to show comments and "Add Comment" button

### CODE REVIEW

**Comment by NarawishS** [comment]
I try it and why are there 2 comment on one blog?

**Comment by NarawishS** [comment]
+1 I think it's good now maybe we need to add like and dislike to comment too?

**Comment by LevNut** [comment]
+1, The comment section works perfectly fine for now, there are posted time and the author name included

**Comment by keyboard2543** [comment]
+1 Comment can be really used and it show its content truely

**Pull request merged**
