### PR TITLE
Tags feature fixes and can be used correctly

### PR DESCRIPTION
**Pull request by keyboard2543**
Let's test this fixed feature. You go to create blog or edit blog then test the tags feature by typing tag. If you want to have multiple tags, You use ',' ti separate tag.

### CODE REVIEW

**Comment by NarawishS** [comment]
Tag become a require field when you create blog, we want that field to be null is True fix it please

**Comment by keyboard2543** [comment]
> @NarawishS Tag become a require field when you create blog, we want that field to be null is True fix it please

Thanks for reply. I have fixed. Please check it out.

**Comment by LevNut** [comment]
Already tested, the features are working fine (can separate each tag by using ","), but the order of the tags sometime are kind of weird organised.

**Comment by NarawishS** [comment]
you didn't use the separate package that i told you to use now there are conflicts try again pal.

**Review by NarawishS — APPROVED** [review]

**Pull request merged**
